// <auto-generated />
using System;
using GastosResidenciaisAPI.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastosResidenciaisAPI.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20260114152704_migracao1")]
    partial class migracao1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.CategoriaAggregate.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("finalidade")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.CompanyAggregate.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.EmployeeAggregate.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("photo")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.PessoaAggregate.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("idade")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.TransacaoAggregate.Transacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("categoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pessoaId")
                        .HasColumnType("integer");

                    b.Property<int>("tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("valor")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("categoriaId");

                    b.HasIndex("pessoaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.TransacaoAggregate.Transacao", b =>
                {
                    b.HasOne("GastosResidenciaisAPI.Domain.Model.CategoriaAggregate.Categoria", "Categoria")
                        .WithMany("transacoes")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastosResidenciaisAPI.Domain.Model.PessoaAggregate.Pessoa", "Pessoa")
                        .WithMany("transacoes")
                        .HasForeignKey("pessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.CategoriaAggregate.Categoria", b =>
                {
                    b.Navigation("transacoes");
                });

            modelBuilder.Entity("GastosResidenciaisAPI.Domain.Model.PessoaAggregate.Pessoa", b =>
                {
                    b.Navigation("transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
